### ISSUE TITLE
Not working under Debian Sid

### ISSUE THREAD

**Issue by Doc73** [ju1ius/uxdgmenu#1]
Hi, I tried you script.

Here is the error:
<code>$ uxm-daemon start -f openbox
Traceback (most recent call last):
  File "/usr/bin/uxm-daemon", line 132, in <module>
    if ns == "device":
NameError: name 'ns' is not defined</code>

P.S.: Please, correct the link to deb!

Hi and thanks!

**Comment by ju1ius** [comment]
Hello,

If you meant the link to the download page in the README, it is fixed now.

Concerning the issue, I haven't been able to reproduce it. Maybe try the latest version (0.3).
I uploaded a new deb package.

**Comment by Doc73** [comment]
Installed latest version, previous error doesn't appear.

However, I still do not see anything on the menu!

I remain available for further debugging.

**Comment by ju1ius** [comment]
Thanks for your help !

I you want to debug the deamon, it is best to start it directly from the command line in non-background mode
`/usr/bin/uxdgmenud -va -f openbox`
Then move around some .desktop files, ie:
`touch ~/.local/share/applications/foobar.desktop && rm ~/.local/share/applications/foobar.desktop`
or try with real .desktop files...
Then check both terminal output and /var/log/user.log
`sudo grep uxdgmenu /var/log/user.log`
And then check the contents of ~/.cache/uxdgmenu/applications.openbox

I'll write a wiki page about debugging when I have more time.

**Comment by Doc73** [comment]
The problem is very complex, because a friend with Wheezy says that everything works perfectly. I, however, am with Sid...

~/.cache/uxdgmenu/applications.openbox, apparently, is correct and...
<code>~$ sudo grep uxdgmenu /var/log/user.log
[sudo] password for domenico: 
Apr  6 01:04:31 eeepc uxdgmenud[22582]: Starting in /home/domenico
Apr  6 01:12:06 eeepc uxdgmenud[22582]: Exiting...
Apr  6 18:22:08 eeepc uxdgmenud[23393]: Starting in /home/domenico
Apr  6 18:22:08 eeepc uxdgmenud[23393]: Ignoring pattern: /.local/share/applications/menu-xdg/
Apr  6 18:22:08 eeepc uxdgmenud[23393]: Watching /home/domenico/.config/menus
Apr  6 18:22:08 eeepc uxdgmenud[23393]: Watching /home/domenico/.local/share/desktop-directories
Apr  6 18:22:08 eeepc uxdgmenud[23393]: Watching /home/domenico/.local/share/applications
Apr  6 18:22:09 eeepc uxdgmenud[23393]: Watching /etc/xdg/menus
Apr  6 18:22:09 eeepc uxdgmenud[23393]: Watching /usr/share/desktop-directories
Apr  6 18:22:09 eeepc uxdgmenud[23393]: Watching /usr/share/applications
Apr  6 18:22:09 eeepc uxdgmenud[23393]: Watching /usr/local/share/applications</code>

I added to menu.xml:
<code>
&lt;menu label="Applicazioni" execute="cat ~/.cache/uxdgmenu/applications.openbox" /&gt;
&lt;menu label="Bookmarks" execute="cat ~/.cache/uxdgmenu/bookmarks.openbox" /&gt;
&lt;menu label="Recenti" execute="cat ~/.cache/uxdgmenu/recent-files.openbox" /&gt;
&lt;menu label="Devices" execute="cat ~/.cache/uxdgmenu/devices.openbox" /&gt;</code>

Maybe I'm wrong something?

P.S.
How can I add xml code here?

**Comment by ju1ius** [comment]
Your last code block is empty...

**Comment by Doc73** [comment]
I know, but I can't understand how to insert xml code here.... :-D

EDIT
Done!!!

**Comment by ju1ius** [comment]
Is the GTK menu working properly ?
You can launch it with:

`````` uxm-menu```
Or use the "show menu" button int the Daemon tab of the config GUI:
```uxm-config```
``````

**Comment by Doc73** [comment]
<code>uxm-config</code> works perfectly, but
<code>
domenico@eeepc:~$ uxm-menu
/usr/lib/uxdgmenu/uxm/dialogs/menu.py:86: GtkWarning: Impossibile trovare il motore del tema in module_path: «equinox»,
  super(Menu, self).**init**()
Traceback (most recent call last):
  File "/usr/bin/uxm-menu", line 10, in <module>
    menu.main()
  File "/usr/lib/uxdgmenu/uxm/dialogs/menu.py", line 112, in main
    self.open()
  File "/usr/lib/uxdgmenu/uxm/dialogs/menu.py", line 105, in open
    self.load_menu()
  File "/usr/lib/uxdgmenu/uxm/dialogs/menu.py", line 131, in load_menu
    self.load_submenu(item, APPS_MENU)
  File "/usr/lib/uxdgmenu/uxm/dialogs/menu.py", line 160, in load_submenu
    for item in self.formatter.format_menu(data):
  File "/usr/lib/uxdgmenu/uxm/dialogs/menu.py", line 49, in format_menu
    return [i for i in self.get_children(data, level)]
  File "/usr/lib/uxdgmenu/uxm/formatter.py", line 72, in get_children
    yield self.format_submenu(item, level+1)
  File "/usr/lib/uxdgmenu/uxm/dialogs/menu.py", line 63, in format_submenu
    for child in self.get_children(data, level):
  File "/usr/lib/uxdgmenu/uxm/formatter.py", line 68, in get_children
    yield self.format_application(item, level+1)
  File "/usr/lib/uxdgmenu/uxm/dialogs/menu.py", line 53, in format_application
    item = self._get_item(data['label'], data['icon'])
  File "/usr/lib/uxdgmenu/uxm/dialogs/menu.py", line 36, in _get_item
    pixbuf = gtk.gdk.pixbuf_new_from_file(icon)
glib.GError: Apertura del file «/usr/share/mp3splt-gtk/mp3splt-gtk_ico.png» non riuscita: File o directory non esistente
</code>

**Comment by ju1ius** [comment]
Looks like there is somthing wrong with your GTK theme:
`/usr/lib/uxdgmenu/uxm/dialogs/menu.py:86: GtkWarning: Impossibile trovare il motore del tema in modulepath: «equinox»,`
And gtk can't find this icon:
`glib.GError: Apertura del file «/usr/share/mp3splt-gtk/mp3splt-gtk_ico.png» non riuscita: File o directory non esistente`

**Comment by Doc73** [comment]
Yes!
I did some investigations and in fact:
<code>domenico@eeepc:~$ locate mp3splt-gtk_ico.png
/usr/share/pixmaps/mp3splt-gtk_ico.png</code>

It therefore seems that the system is looking for the icon in a wrong path.
I'll report the bug to the Debian Bug Tracking!

**Comment by ju1ius** [comment]
But I still doesn't see why your openbox menu doesn't show...
Can you make a gist with the contents of your applications.openbox ?

**Comment by ju1ius** [comment]
Could you also try to run:
`uxm-daemon update:applications -f openbox`
and see if it complains about something ?

**Comment by Doc73** [comment]
<code>domenico@eeepc:~$ uxm-daemon update:applications -f openbox
/usr/lib/uxdgmenu/uxm/icon_finder.py:21: GtkWarning: Impossibile trovare il motore del tema in module_path: «equinox»,
  gtk_settings = gtk.settings_get_default()</code>
It constantly complains about equinox, but I do not think this is the problem.

The file applications.openbox is apparently correct, but is not loaded in the menu.

**Comment by ju1ius** [comment]
Have you tried to reconfigure or restart openbox ?

**Comment by Doc73** [comment]
Yes! Obvious!

I will try to contact my friend with Wheezy to see what happens on his system. :(

**Comment by Doc73** [comment]
Just tried with FluxBox: it works perfectly!

The mystery deepens!!!

**Comment by ju1ius** [comment]
Hmmm, it reminds me of an issue I had with openbox.
At the time it seemed that openbox was caching the calls to the execute command of the menu item.
However the issue disappeared when I upgraded to openbox 3.5.
What version are you using ?

**Comment by ju1ius** [comment]
By the way have you tried to delete the content of your `~/.cache/uxdgmenu/` directory and restarting the daemon ?

**Comment by Doc73** [comment]
Openbox 3.5.0

I deleted <code>~/.cache/uxdgmenu</code> many times, but without success!

**Comment by Doc73** [comment]
I got it!!!!!!!!!!
In <code>menu.xml</code>, we have to insert, ex. gr.,
<code>&lt;menu label="Applicazioni" id="Applications" execute="cat ~/.cache/uxdgmenu/applications.openbox"/&gt;</code>
In short, we need the parameter "id=".
Please, correct the wiki!

Hi and thank you,
Domenico

**Comment by ju1ius** [comment]
Thanks, I updated the Wiki page !
;-)
