### ISSUE TITLE
root menu preview is different from the actual generated menu (openbox)

### ISSUE THREAD

**Issue by Milozzy** [ju1ius/uxdgmenu#2]
Hi dear ju1ius,
first of all let me thank you for this brilliant application.

Here's the issue that I discoverd: like the title said, when I preview the root menu with the config GUI I see one root menu, but when I use the generated root menu I see another (less good) root menu.

Here's a couple of screenshots:

preview:
http://ompldr.org/vZGNtMw

generated ~/.cache/uxdgmenu/rootmenu.openbox
http://ompldr.org/vZGNtNA

Looking at  ~/.cache/uxdgmenu/rootmenu.openbox one clear problem is this line   

menu id="uxm-applications" label="Applicazioni" execute="cat /home/milo/.cache/uxdgmenu/uxm-applications.menu.openbox" icon="/usr/share/icons/gnome/16x16/categories/applications-other.png"

instead of this one:

menu id="uxm-applications" label="Applicazioni" execute="cat /home/milo/.cache/uxdgmenu/applications.openbox" icon="/usr/share/icons/gnome/16x16/categories/applications-other.png"

This is easy to fix, but do not explain why the preview is different and as you can see there are other differences: in the preview there is "Home", "uxm-menu" and "exit" entries, while in the generated root menu there are not. Plus, icons are not scaled well in the generated one.

Just one another small problem: you use "Usati di recente" label for both recently and devices pipemenus, while a correct label for the device one would be "Dispositivi removibili" ;)

I have those problem on my Debian Sid 32bit System.

Thanks for all your efforts and feel free to ask me more infos.

Bye!

Marco Milone

**Comment by ju1ius** [comment]
At first glance, it seems to me that you have old config files from previous versions remaining on your filesystem.
I would suggest this:
- Delete the contents of your `~/.cache/uxdgmenu` and `~/.config/uxdgmenu` folders:

``` bash
rm ~/.cache/uxdgmenu/* ~/.config/uxdgmenu/*
```
- Optionally tune you config:

``` bash
uxm-config
```
- Regenerate the menus:

``` sh
uxm-daemon update:all
```
- Then copy the rootmenu cache file to your openbox config folder:

``` bash
mv ~/.config/openbox/menu.xml ~/.config/openbox/menu.xml.bak
mv ~/.cache/uxdgmenu/rootmenu.openbox ~/.config/openbox/menu.xml
```
- For the "Home folder" menu to work, you'll then need to manually add an entry to `~/.config/openbox/menu.xml`:

``` xml
<menu label="Posti" id="uxm-places" execute="uxm-places -f openbox" />
```

> Here's the issue that I discoverd: like the title said, when I preview the root menu with the config GUI I see one root menu, but when I use the generated root menu I see another (less good) root menu.

Some of the differences are normal. The "preview" menu is a standalone menu (built only in GTK) that can be used independently of any window manager (ie by binding a keystroke to the `uxm-menu` command).  The other one is generated by Openbox (or Fluxbox, etc...), so there will always be some slight discrepancies. For example, GTK and Openbox don't use the same mechanism for resizing icons.

Don't hesitate to ask if your issues persist.
;-)

**Comment by Milozzy** [comment]
hi again and thank you very much for your time and explanations!

Unfortunately, follow all the steps above but the problem is still present: I have to manually modify 

menu id="uxm-applications" label="Applicazioni" execute="cat /home/milo/.cache/uxdgmenu/uxm-applications.menu.openbox" icon="/usr/share/icons/gnome/16x16/categories/applications-other.png"

and exit submenu is not generated.

Thank you again

**Comment by ju1ius** [comment]
In uxm-config, check Menus > Applications > Menu file. What files are listed there ?

**Comment by ju1ius** [comment]
Ok, I spotted the issue. I'll update as soon as I can !

**Comment by Milozzy** [comment]
Menus > Applications > Menu file:
- uxm-applications.menu
- gnome-applications.menu
- xfce-applications.menu
- uxm-rootmenu.menu
- debian-menu.menu

Thanks again!

**Comment by Milozzy** [comment]
I just tried the new package, after deleting all the previous config and generated files.

Now the applications pipemenu works, but there are still some issues:
- a syntax error in the .xml code
- no exit and no uxm-menu entries 

scrot: http://ompldr.org/vZGQwNA

Sorry if I bother you, but I really like your work and I am willing to help.

Bye and thanks!

**Comment by ju1ius** [comment]
> Sorry if I bother you, but I really like your work and I am willing to help.

You don't bother me, in fact you're even helping me out ;-)

Can you run 

```
uxm-daemon update:apps -f openbox
```

in a terminal and tell me if you see some errors ?

I also need to see the contents of your `~/.cache/uxdgmenu/applications.openbox` `~/.cache/uxdgmenu/rootmenu.openbox` and `/etc/xdg/menus/uxm-rootmenu.menu` files.
Please [create some gists](https://gist.github.com/) and send me the links.

Thanks.

**Comment by Milozzy** [comment]
uxm-daemon update:apps -f openbox reported no errors.

Here's the files: https://gist.github.com/2383169

As you can see, the problem is in ~/.cache/rootmenu.openbox: in the file there are several syntax errors.
For example, line 28 is missing some quotes: 

menu id=uxm-menu

should be 

<menu id="uxm-menu"

This is not the only one.

Hope this helps.

Thanks again and feel free to ask me more infos!

**Comment by ju1ius** [comment]
Hi !
I uploaded version 0.5 in the downloads section.
Can you test it to see if your issues are fixed ?

**Comment by Milozzy** [comment]
Hi!
I tested it and it is almost perfect!
Just one small issue: the uxm submenu shows the path of the icon instead of the actual label...
Pic: http://ompldr.org/vZHE3aQ

The problem is in this part of the generated rootmenu.openbox:

menu id="Altro" label="/home/milo/.icons/Faience/categories/32/applications-other.png"

**Comment by ju1ius** [comment]
Hi !
I uploaded version 0.6 in the downloads section.
Can you test it to see if your issues are fixed ?
