### ISSUE TITLE
problems getting uxdgmenu installed and working

### ISSUE THREAD

**Issue by AlisterH** [ju1ius/uxdgmenu#4]
The instructions say to use 'make install --prefix='.  This doesn't work - it doesn't accept the ' --prefix=' parameter. 
So I guess the instructions should say to edit the variable in the makefile.

**Comment by ju1ius** [comment]
Hi,
this is a documentation bug.
You now have to call:

``` bash
make && sudo make install --prefix=/usr
```

for the build to succeed.

Can you try it and post the output of the command if it fails ?
Don't forget to run `make clean` first if you already attempted to build.

**Comment by AlisterH** [comment]
Oh - I think you mean to say without the "--":

make install prefix=/usr

That resolves the 2nd issue.
